/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace IIsolationModeWrapperTraderV2 {
  export type CreateActionsForWrappingParamsStruct = {
    primaryAccountId: BigNumberish;
    otherAccountId: BigNumberish;
    primaryAccountOwner: string;
    primaryAccountNumber: BigNumberish;
    otherAccountOwner: string;
    otherAccountNumber: BigNumberish;
    outputMarket: BigNumberish;
    inputMarket: BigNumberish;
    minOutputAmount: BigNumberish;
    inputAmount: BigNumberish;
    orderData: BytesLike;
  };

  export type CreateActionsForWrappingParamsStructOutput = [
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ] & {
    primaryAccountId: BigNumber;
    otherAccountId: BigNumber;
    primaryAccountOwner: string;
    primaryAccountNumber: BigNumber;
    otherAccountOwner: string;
    otherAccountNumber: BigNumber;
    outputMarket: BigNumber;
    inputMarket: BigNumber;
    minOutputAmount: BigNumber;
    inputAmount: BigNumber;
    orderData: string;
  };
}

export declare namespace IDolomiteStructs {
  export type AssetAmountStruct = {
    sign: boolean;
    denomination: BigNumberish;
    ref: BigNumberish;
    value: BigNumberish;
  };

  export type AssetAmountStructOutput = [boolean, number, number, BigNumber] & {
    sign: boolean;
    denomination: number;
    ref: number;
    value: BigNumber;
  };

  export type ActionArgsStruct = {
    actionType: BigNumberish;
    accountId: BigNumberish;
    amount: IDolomiteStructs.AssetAmountStruct;
    primaryMarketId: BigNumberish;
    secondaryMarketId: BigNumberish;
    otherAddress: string;
    otherAccountId: BigNumberish;
    data: BytesLike;
  };

  export type ActionArgsStructOutput = [
    number,
    BigNumber,
    IDolomiteStructs.AssetAmountStructOutput,
    BigNumber,
    BigNumber,
    string,
    BigNumber,
    string
  ] & {
    actionType: number;
    accountId: BigNumber;
    amount: IDolomiteStructs.AssetAmountStructOutput;
    primaryMarketId: BigNumber;
    secondaryMarketId: BigNumber;
    otherAddress: string;
    otherAccountId: BigNumber;
    data: string;
  };
}

export interface JonesUSDCIsolationModeWrapperTraderV2Interface
  extends utils.Interface {
  functions: {
    "DOLOMITE_MARGIN()": FunctionFragment;
    "DOLOMITE_REGISTRY()": FunctionFragment;
    "JONES_USDC_REGISTRY()": FunctionFragment;
    "USDC()": FunctionFragment;
    "VAULT_FACTORY()": FunctionFragment;
    "actionsLength()": FunctionFragment;
    "createActionsForWrapping((uint256,uint256,address,uint256,address,uint256,uint256,uint256,uint256,uint256,bytes))": FunctionFragment;
    "exchange(address,address,address,address,uint256,bytes)": FunctionFragment;
    "getExchangeCost(address,address,uint256,bytes)": FunctionFragment;
    "isValidInputToken(address)": FunctionFragment;
    "token()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DOLOMITE_MARGIN"
      | "DOLOMITE_REGISTRY"
      | "JONES_USDC_REGISTRY"
      | "USDC"
      | "VAULT_FACTORY"
      | "actionsLength"
      | "createActionsForWrapping"
      | "exchange"
      | "getExchangeCost"
      | "isValidInputToken"
      | "token"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DOLOMITE_MARGIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DOLOMITE_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "JONES_USDC_REGISTRY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "VAULT_FACTORY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "actionsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createActionsForWrapping",
    values: [IIsolationModeWrapperTraderV2.CreateActionsForWrappingParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "exchange",
    values: [string, string, string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExchangeCost",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidInputToken",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DOLOMITE_MARGIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DOLOMITE_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "JONES_USDC_REGISTRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "VAULT_FACTORY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "actionsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createActionsForWrapping",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exchange", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getExchangeCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidInputToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;

  events: {};
}

export interface JonesUSDCIsolationModeWrapperTraderV2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: JonesUSDCIsolationModeWrapperTraderV2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<[string]>;

    DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<[string]>;

    JONES_USDC_REGISTRY(overrides?: CallOverrides): Promise<[string]>;

    USDC(overrides?: CallOverrides): Promise<[string]>;

    VAULT_FACTORY(overrides?: CallOverrides): Promise<[string]>;

    actionsLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    createActionsForWrapping(
      _params: IIsolationModeWrapperTraderV2.CreateActionsForWrappingParamsStruct,
      overrides?: CallOverrides
    ): Promise<[IDolomiteStructs.ActionArgsStructOutput[]]>;

    exchange(
      _tradeOriginator: string,
      _receiver: string,
      _outputToken: string,
      _inputToken: string,
      _inputAmount: BigNumberish,
      _orderData: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getExchangeCost(
      _inputToken: string,
      _outputToken: string,
      _desiredInputAmount: BigNumberish,
      _orderData: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isValidInputToken(
      _inputToken: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    token(overrides?: CallOverrides): Promise<[string]>;
  };

  DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<string>;

  DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<string>;

  JONES_USDC_REGISTRY(overrides?: CallOverrides): Promise<string>;

  USDC(overrides?: CallOverrides): Promise<string>;

  VAULT_FACTORY(overrides?: CallOverrides): Promise<string>;

  actionsLength(overrides?: CallOverrides): Promise<BigNumber>;

  createActionsForWrapping(
    _params: IIsolationModeWrapperTraderV2.CreateActionsForWrappingParamsStruct,
    overrides?: CallOverrides
  ): Promise<IDolomiteStructs.ActionArgsStructOutput[]>;

  exchange(
    _tradeOriginator: string,
    _receiver: string,
    _outputToken: string,
    _inputToken: string,
    _inputAmount: BigNumberish,
    _orderData: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getExchangeCost(
    _inputToken: string,
    _outputToken: string,
    _desiredInputAmount: BigNumberish,
    _orderData: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isValidInputToken(
    _inputToken: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  token(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<string>;

    DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<string>;

    JONES_USDC_REGISTRY(overrides?: CallOverrides): Promise<string>;

    USDC(overrides?: CallOverrides): Promise<string>;

    VAULT_FACTORY(overrides?: CallOverrides): Promise<string>;

    actionsLength(overrides?: CallOverrides): Promise<BigNumber>;

    createActionsForWrapping(
      _params: IIsolationModeWrapperTraderV2.CreateActionsForWrappingParamsStruct,
      overrides?: CallOverrides
    ): Promise<IDolomiteStructs.ActionArgsStructOutput[]>;

    exchange(
      _tradeOriginator: string,
      _receiver: string,
      _outputToken: string,
      _inputToken: string,
      _inputAmount: BigNumberish,
      _orderData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getExchangeCost(
      _inputToken: string,
      _outputToken: string,
      _desiredInputAmount: BigNumberish,
      _orderData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidInputToken(
      _inputToken: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    token(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<BigNumber>;

    DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<BigNumber>;

    JONES_USDC_REGISTRY(overrides?: CallOverrides): Promise<BigNumber>;

    USDC(overrides?: CallOverrides): Promise<BigNumber>;

    VAULT_FACTORY(overrides?: CallOverrides): Promise<BigNumber>;

    actionsLength(overrides?: CallOverrides): Promise<BigNumber>;

    createActionsForWrapping(
      _params: IIsolationModeWrapperTraderV2.CreateActionsForWrappingParamsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    exchange(
      _tradeOriginator: string,
      _receiver: string,
      _outputToken: string,
      _inputToken: string,
      _inputAmount: BigNumberish,
      _orderData: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getExchangeCost(
      _inputToken: string,
      _outputToken: string,
      _desiredInputAmount: BigNumberish,
      _orderData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidInputToken(
      _inputToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DOLOMITE_MARGIN(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DOLOMITE_REGISTRY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    JONES_USDC_REGISTRY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    USDC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    VAULT_FACTORY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    actionsLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createActionsForWrapping(
      _params: IIsolationModeWrapperTraderV2.CreateActionsForWrappingParamsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    exchange(
      _tradeOriginator: string,
      _receiver: string,
      _outputToken: string,
      _inputToken: string,
      _inputAmount: BigNumberish,
      _orderData: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getExchangeCost(
      _inputToken: string,
      _outputToken: string,
      _desiredInputAmount: BigNumberish,
      _orderData: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidInputToken(
      _inputToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
