/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGmxDataStore } from "./IGmxDataStore";
export type { IGmxDepositCallbackReceiver } from "./IGmxDepositCallbackReceiver";
export type { IGmxDepositHandler } from "./IGmxDepositHandler";
export type { IGmxEventEmitter } from "./IGmxEventEmitter";
export type { IGmxExchangeRouter } from "./IGmxExchangeRouter";
export type { IGmxMarketToken } from "./IGmxMarketToken";
export type { IGmxOracle } from "./IGmxOracle";
export type { IGmxReader } from "./IGmxReader";
export type { IGmxRoleStore } from "./IGmxRoleStore";
export type { IGmxRouter } from "./IGmxRouter";
export type { IGmxV2IsolationModeTokenVaultV1 } from "./IGmxV2IsolationModeTokenVaultV1";
export type { IGmxV2IsolationModeUnwrapperTraderV2 } from "./IGmxV2IsolationModeUnwrapperTraderV2";
export type { IGmxV2IsolationModeVaultFactory } from "./IGmxV2IsolationModeVaultFactory";
export type { IGmxV2IsolationModeWrapperTraderV2 } from "./IGmxV2IsolationModeWrapperTraderV2";
export type { IGmxV2MarketTokenPriceOracle } from "./IGmxV2MarketTokenPriceOracle";
export type { IGmxV2Registry } from "./IGmxV2Registry";
export type { IGmxWithdrawalCallbackReceiver } from "./IGmxWithdrawalCallbackReceiver";
export type { IGmxWithdrawalHandler } from "./IGmxWithdrawalHandler";
