/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestVesterImplementationV1 } from "./TestVesterImplementationV1";
export type { TestVesterImplementationV2 } from "./TestVesterImplementationV2";
