/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDolomiteMarginCallee,
  IDolomiteMarginCalleeInterface,
} from "../../../../../../@dolomite-exchange/modules-base/contracts/protocol/interfaces/IDolomiteMarginCallee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        components: [
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "number",
            type: "uint256",
          },
        ],
        internalType: "struct IDolomiteStructs.AccountInfo",
        name: "_accountInfo",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "callFunction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDolomiteMarginCallee__factory {
  static readonly abi = _abi;
  static createInterface(): IDolomiteMarginCalleeInterface {
    return new utils.Interface(_abi) as IDolomiteMarginCalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDolomiteMarginCallee {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IDolomiteMarginCallee;
  }
}
