/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IUmamiAggregateVault } from "./IUmamiAggregateVault";
export type { IUmamiAssetVault } from "./IUmamiAssetVault";
export type { IUmamiAssetVaultIsolationModeTokenVaultV1 } from "./IUmamiAssetVaultIsolationModeTokenVaultV1";
export type { IUmamiAssetVaultIsolationModeVaultFactory } from "./IUmamiAssetVaultIsolationModeVaultFactory";
export type { IUmamiAssetVaultRegistry } from "./IUmamiAssetVaultRegistry";
export type { IUmamiAssetVaultStorageViewer } from "./IUmamiAssetVaultStorageViewer";
export type { IUmamiAssetVaultWhitelist } from "./IUmamiAssetVaultWhitelist";
