/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as modulesBase from "./modules-base";
export type { modulesBase };
import type * as modulesOracles from "./modules-oracles";
export type { modulesOracles };
