/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface IUSDCRegistryInterface extends utils.Interface {
  functions: {
    "aaveLendingPool()": FunctionFragment;
    "dolomiteRegistry()": FunctionFragment;
    "ownerSetAaveLendingPool(address)": FunctionFragment;
    "ownerSetDolomiteRegistry(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "aaveLendingPool"
      | "dolomiteRegistry"
      | "ownerSetAaveLendingPool"
      | "ownerSetDolomiteRegistry"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "aaveLendingPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dolomiteRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetAaveLendingPool",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetDolomiteRegistry",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "aaveLendingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dolomiteRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetAaveLendingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetDolomiteRegistry",
    data: BytesLike
  ): Result;

  events: {
    "AaveLendingPoolSet(address)": EventFragment;
    "DolomiteRegistrySet(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AaveLendingPoolSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DolomiteRegistrySet"): EventFragment;
}

export interface AaveLendingPoolSetEventObject {
  _aaveLendingPool: string;
}
export type AaveLendingPoolSetEvent = TypedEvent<
  [string],
  AaveLendingPoolSetEventObject
>;

export type AaveLendingPoolSetEventFilter =
  TypedEventFilter<AaveLendingPoolSetEvent>;

export interface DolomiteRegistrySetEventObject {
  _dolomiteRegistry: string;
}
export type DolomiteRegistrySetEvent = TypedEvent<
  [string],
  DolomiteRegistrySetEventObject
>;

export type DolomiteRegistrySetEventFilter =
  TypedEventFilter<DolomiteRegistrySetEvent>;

export interface IUSDCRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IUSDCRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    aaveLendingPool(overrides?: CallOverrides): Promise<[string]>;

    dolomiteRegistry(overrides?: CallOverrides): Promise<[string]>;

    ownerSetAaveLendingPool(
      _aaveLendingPool: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetDolomiteRegistry(
      _dolomiteRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  aaveLendingPool(overrides?: CallOverrides): Promise<string>;

  dolomiteRegistry(overrides?: CallOverrides): Promise<string>;

  ownerSetAaveLendingPool(
    _aaveLendingPool: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetDolomiteRegistry(
    _dolomiteRegistry: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    aaveLendingPool(overrides?: CallOverrides): Promise<string>;

    dolomiteRegistry(overrides?: CallOverrides): Promise<string>;

    ownerSetAaveLendingPool(
      _aaveLendingPool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetDolomiteRegistry(
      _dolomiteRegistry: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AaveLendingPoolSet(address)"(
      _aaveLendingPool?: string | null
    ): AaveLendingPoolSetEventFilter;
    AaveLendingPoolSet(
      _aaveLendingPool?: string | null
    ): AaveLendingPoolSetEventFilter;

    "DolomiteRegistrySet(address)"(
      _dolomiteRegistry?: string | null
    ): DolomiteRegistrySetEventFilter;
    DolomiteRegistrySet(
      _dolomiteRegistry?: string | null
    ): DolomiteRegistrySetEventFilter;
  };

  estimateGas: {
    aaveLendingPool(overrides?: CallOverrides): Promise<BigNumber>;

    dolomiteRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    ownerSetAaveLendingPool(
      _aaveLendingPool: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetDolomiteRegistry(
      _dolomiteRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    aaveLendingPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dolomiteRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ownerSetAaveLendingPool(
      _aaveLendingPool: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetDolomiteRegistry(
      _dolomiteRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
