/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAuthorizationBase__factory } from "./IAuthorizationBase__factory";
export { IBaseRegistry__factory } from "./IBaseRegistry__factory";
export { IBorrowPositionProxyV1__factory } from "./IBorrowPositionProxyV1__factory";
export { IBorrowPositionProxyV2__factory } from "./IBorrowPositionProxyV2__factory";
export { IDolomiteAccountRegistry__factory } from "./IDolomiteAccountRegistry__factory";
export { IDolomiteMigrator__factory } from "./IDolomiteMigrator__factory";
export { IDolomiteRegistry__factory } from "./IDolomiteRegistry__factory";
export { IEventEmitterRegistry__factory } from "./IEventEmitterRegistry__factory";
export { IExpiry__factory } from "./IExpiry__factory";
export { IExpiryV2__factory } from "./IExpiryV2__factory";
export { IGenericTraderProxyV1__factory } from "./IGenericTraderProxyV1__factory";
export { ILiquidatorAssetRegistry__factory } from "./ILiquidatorAssetRegistry__factory";
export { IOnlyDolomiteMargin__factory } from "./IOnlyDolomiteMargin__factory";
