/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  OnlyDolomiteMargin,
  OnlyDolomiteMarginInterface,
} from "../../../../../@dolomite-exchange/modules-base/contracts/helpers/OnlyDolomiteMargin";

const _abi = [
  {
    inputs: [],
    name: "DOLOMITE_MARGIN",
    outputs: [
      {
        internalType: "contract IDolomiteMargin",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DOLOMITE_MARGIN_OWNER",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class OnlyDolomiteMargin__factory {
  static readonly abi = _abi;
  static createInterface(): OnlyDolomiteMarginInterface {
    return new utils.Interface(_abi) as OnlyDolomiteMarginInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OnlyDolomiteMargin {
    return new Contract(address, _abi, signerOrProvider) as OnlyDolomiteMargin;
  }
}
