/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export interface IDolomiteRegistryInterface extends utils.Interface {
  functions: {
    "chainlinkPriceOracle()": FunctionFragment;
    "dolomiteAccountRegistry()": FunctionFragment;
    "dolomiteMigrator()": FunctionFragment;
    "eventEmitter()": FunctionFragment;
    "expiry()": FunctionFragment;
    "genericTraderProxy()": FunctionFragment;
    "lazyInitialize(address,address)": FunctionFragment;
    "liquidatorAssetRegistry()": FunctionFragment;
    "oracleAggregator()": FunctionFragment;
    "ownerSetChainlinkPriceOracle(address)": FunctionFragment;
    "ownerSetDolomiteAccountRegistry(address)": FunctionFragment;
    "ownerSetDolomiteMigrator(address)": FunctionFragment;
    "ownerSetEventEmitter(address)": FunctionFragment;
    "ownerSetExpiry(address)": FunctionFragment;
    "ownerSetGenericTraderProxy(address)": FunctionFragment;
    "ownerSetLiquidatorAssetRegistry(address)": FunctionFragment;
    "ownerSetOracleAggregator(address)": FunctionFragment;
    "ownerSetRedstonePriceOracle(address)": FunctionFragment;
    "ownerSetSlippageToleranceForPauseSentinel(uint256)": FunctionFragment;
    "redstonePriceOracle()": FunctionFragment;
    "slippageToleranceForPauseSentinel()": FunctionFragment;
    "slippageToleranceForPauseSentinelBase()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "chainlinkPriceOracle"
      | "dolomiteAccountRegistry"
      | "dolomiteMigrator"
      | "eventEmitter"
      | "expiry"
      | "genericTraderProxy"
      | "lazyInitialize"
      | "liquidatorAssetRegistry"
      | "oracleAggregator"
      | "ownerSetChainlinkPriceOracle"
      | "ownerSetDolomiteAccountRegistry"
      | "ownerSetDolomiteMigrator"
      | "ownerSetEventEmitter"
      | "ownerSetExpiry"
      | "ownerSetGenericTraderProxy"
      | "ownerSetLiquidatorAssetRegistry"
      | "ownerSetOracleAggregator"
      | "ownerSetRedstonePriceOracle"
      | "ownerSetSlippageToleranceForPauseSentinel"
      | "redstonePriceOracle"
      | "slippageToleranceForPauseSentinel"
      | "slippageToleranceForPauseSentinelBase"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "chainlinkPriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dolomiteAccountRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dolomiteMigrator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eventEmitter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "expiry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "genericTraderProxy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lazyInitialize",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidatorAssetRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleAggregator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetChainlinkPriceOracle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetDolomiteAccountRegistry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetDolomiteMigrator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetEventEmitter",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetExpiry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetGenericTraderProxy",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetLiquidatorAssetRegistry",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetOracleAggregator",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetRedstonePriceOracle",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerSetSlippageToleranceForPauseSentinel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redstonePriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "slippageToleranceForPauseSentinel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "slippageToleranceForPauseSentinelBase",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "chainlinkPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dolomiteAccountRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dolomiteMigrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventEmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "expiry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "genericTraderProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lazyInitialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidatorAssetRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleAggregator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetChainlinkPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetDolomiteAccountRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetDolomiteMigrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetEventEmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetExpiry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetGenericTraderProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetLiquidatorAssetRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetOracleAggregator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetRedstonePriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerSetSlippageToleranceForPauseSentinel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "redstonePriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slippageToleranceForPauseSentinel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slippageToleranceForPauseSentinelBase",
    data: BytesLike
  ): Result;

  events: {
    "ChainlinkPriceOracleSet(address)": EventFragment;
    "DolomiteAccountRegistrySet(address)": EventFragment;
    "DolomiteMigratorSet(address)": EventFragment;
    "EventEmitterSet(address)": EventFragment;
    "ExpirySet(address)": EventFragment;
    "GenericTraderProxySet(address)": EventFragment;
    "LiquidatorAssetRegistrySet(address)": EventFragment;
    "OracleAggregatorSet(address)": EventFragment;
    "RedstonePriceOracleSet(address)": EventFragment;
    "SlippageToleranceForPauseSentinelSet(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChainlinkPriceOracleSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DolomiteAccountRegistrySet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DolomiteMigratorSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EventEmitterSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExpirySet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GenericTraderProxySet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LiquidatorAssetRegistrySet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OracleAggregatorSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RedstonePriceOracleSet"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "SlippageToleranceForPauseSentinelSet"
  ): EventFragment;
}

export interface ChainlinkPriceOracleSetEventObject {
  _chainlinkPriceOracle: string;
}
export type ChainlinkPriceOracleSetEvent = TypedEvent<
  [string],
  ChainlinkPriceOracleSetEventObject
>;

export type ChainlinkPriceOracleSetEventFilter =
  TypedEventFilter<ChainlinkPriceOracleSetEvent>;

export interface DolomiteAccountRegistrySetEventObject {
  _dolomiteAccountRegistry: string;
}
export type DolomiteAccountRegistrySetEvent = TypedEvent<
  [string],
  DolomiteAccountRegistrySetEventObject
>;

export type DolomiteAccountRegistrySetEventFilter =
  TypedEventFilter<DolomiteAccountRegistrySetEvent>;

export interface DolomiteMigratorSetEventObject {
  _dolomiteMigrator: string;
}
export type DolomiteMigratorSetEvent = TypedEvent<
  [string],
  DolomiteMigratorSetEventObject
>;

export type DolomiteMigratorSetEventFilter =
  TypedEventFilter<DolomiteMigratorSetEvent>;

export interface EventEmitterSetEventObject {
  _eventEmitter: string;
}
export type EventEmitterSetEvent = TypedEvent<
  [string],
  EventEmitterSetEventObject
>;

export type EventEmitterSetEventFilter = TypedEventFilter<EventEmitterSetEvent>;

export interface ExpirySetEventObject {
  _expiry: string;
}
export type ExpirySetEvent = TypedEvent<[string], ExpirySetEventObject>;

export type ExpirySetEventFilter = TypedEventFilter<ExpirySetEvent>;

export interface GenericTraderProxySetEventObject {
  _genericTraderProxy: string;
}
export type GenericTraderProxySetEvent = TypedEvent<
  [string],
  GenericTraderProxySetEventObject
>;

export type GenericTraderProxySetEventFilter =
  TypedEventFilter<GenericTraderProxySetEvent>;

export interface LiquidatorAssetRegistrySetEventObject {
  _liquidatorAssetRegistry: string;
}
export type LiquidatorAssetRegistrySetEvent = TypedEvent<
  [string],
  LiquidatorAssetRegistrySetEventObject
>;

export type LiquidatorAssetRegistrySetEventFilter =
  TypedEventFilter<LiquidatorAssetRegistrySetEvent>;

export interface OracleAggregatorSetEventObject {
  _oracleAggregator: string;
}
export type OracleAggregatorSetEvent = TypedEvent<
  [string],
  OracleAggregatorSetEventObject
>;

export type OracleAggregatorSetEventFilter =
  TypedEventFilter<OracleAggregatorSetEvent>;

export interface RedstonePriceOracleSetEventObject {
  _redstonePriceOracle: string;
}
export type RedstonePriceOracleSetEvent = TypedEvent<
  [string],
  RedstonePriceOracleSetEventObject
>;

export type RedstonePriceOracleSetEventFilter =
  TypedEventFilter<RedstonePriceOracleSetEvent>;

export interface SlippageToleranceForPauseSentinelSetEventObject {
  _slippageTolerance: BigNumber;
}
export type SlippageToleranceForPauseSentinelSetEvent = TypedEvent<
  [BigNumber],
  SlippageToleranceForPauseSentinelSetEventObject
>;

export type SlippageToleranceForPauseSentinelSetEventFilter =
  TypedEventFilter<SlippageToleranceForPauseSentinelSetEvent>;

export interface IDolomiteRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDolomiteRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    chainlinkPriceOracle(overrides?: CallOverrides): Promise<[string]>;

    dolomiteAccountRegistry(overrides?: CallOverrides): Promise<[string]>;

    dolomiteMigrator(overrides?: CallOverrides): Promise<[string]>;

    eventEmitter(overrides?: CallOverrides): Promise<[string]>;

    expiry(overrides?: CallOverrides): Promise<[string]>;

    genericTraderProxy(overrides?: CallOverrides): Promise<[string]>;

    lazyInitialize(
      _dolomiteMigrator: string,
      _oracleAggregator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    liquidatorAssetRegistry(overrides?: CallOverrides): Promise<[string]>;

    oracleAggregator(overrides?: CallOverrides): Promise<[string]>;

    ownerSetChainlinkPriceOracle(
      _chainlinkPriceOracle: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetDolomiteAccountRegistry(
      _dolomiteAccountRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetDolomiteMigrator(
      _dolomiteMigrator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetEventEmitter(
      _eventEmitter: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetExpiry(
      _expiry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetGenericTraderProxy(
      _genericTraderProxy: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetLiquidatorAssetRegistry(
      _liquidatorRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetOracleAggregator(
      _oracleAggregator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetRedstonePriceOracle(
      _redstonePriceOracle: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    ownerSetSlippageToleranceForPauseSentinel(
      _slippageToleranceForPauseSentinel: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    redstonePriceOracle(overrides?: CallOverrides): Promise<[string]>;

    slippageToleranceForPauseSentinel(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    slippageToleranceForPauseSentinelBase(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  chainlinkPriceOracle(overrides?: CallOverrides): Promise<string>;

  dolomiteAccountRegistry(overrides?: CallOverrides): Promise<string>;

  dolomiteMigrator(overrides?: CallOverrides): Promise<string>;

  eventEmitter(overrides?: CallOverrides): Promise<string>;

  expiry(overrides?: CallOverrides): Promise<string>;

  genericTraderProxy(overrides?: CallOverrides): Promise<string>;

  lazyInitialize(
    _dolomiteMigrator: string,
    _oracleAggregator: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  liquidatorAssetRegistry(overrides?: CallOverrides): Promise<string>;

  oracleAggregator(overrides?: CallOverrides): Promise<string>;

  ownerSetChainlinkPriceOracle(
    _chainlinkPriceOracle: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetDolomiteAccountRegistry(
    _dolomiteAccountRegistry: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetDolomiteMigrator(
    _dolomiteMigrator: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetEventEmitter(
    _eventEmitter: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetExpiry(
    _expiry: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetGenericTraderProxy(
    _genericTraderProxy: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetLiquidatorAssetRegistry(
    _liquidatorRegistry: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetOracleAggregator(
    _oracleAggregator: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetRedstonePriceOracle(
    _redstonePriceOracle: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  ownerSetSlippageToleranceForPauseSentinel(
    _slippageToleranceForPauseSentinel: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  redstonePriceOracle(overrides?: CallOverrides): Promise<string>;

  slippageToleranceForPauseSentinel(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  slippageToleranceForPauseSentinelBase(
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    chainlinkPriceOracle(overrides?: CallOverrides): Promise<string>;

    dolomiteAccountRegistry(overrides?: CallOverrides): Promise<string>;

    dolomiteMigrator(overrides?: CallOverrides): Promise<string>;

    eventEmitter(overrides?: CallOverrides): Promise<string>;

    expiry(overrides?: CallOverrides): Promise<string>;

    genericTraderProxy(overrides?: CallOverrides): Promise<string>;

    lazyInitialize(
      _dolomiteMigrator: string,
      _oracleAggregator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    liquidatorAssetRegistry(overrides?: CallOverrides): Promise<string>;

    oracleAggregator(overrides?: CallOverrides): Promise<string>;

    ownerSetChainlinkPriceOracle(
      _chainlinkPriceOracle: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetDolomiteAccountRegistry(
      _dolomiteAccountRegistry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetDolomiteMigrator(
      _dolomiteMigrator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetEventEmitter(
      _eventEmitter: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetExpiry(_expiry: string, overrides?: CallOverrides): Promise<void>;

    ownerSetGenericTraderProxy(
      _genericTraderProxy: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetLiquidatorAssetRegistry(
      _liquidatorRegistry: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetOracleAggregator(
      _oracleAggregator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetRedstonePriceOracle(
      _redstonePriceOracle: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ownerSetSlippageToleranceForPauseSentinel(
      _slippageToleranceForPauseSentinel: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    redstonePriceOracle(overrides?: CallOverrides): Promise<string>;

    slippageToleranceForPauseSentinel(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    slippageToleranceForPauseSentinelBase(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "ChainlinkPriceOracleSet(address)"(
      _chainlinkPriceOracle?: string | null
    ): ChainlinkPriceOracleSetEventFilter;
    ChainlinkPriceOracleSet(
      _chainlinkPriceOracle?: string | null
    ): ChainlinkPriceOracleSetEventFilter;

    "DolomiteAccountRegistrySet(address)"(
      _dolomiteAccountRegistry?: string | null
    ): DolomiteAccountRegistrySetEventFilter;
    DolomiteAccountRegistrySet(
      _dolomiteAccountRegistry?: string | null
    ): DolomiteAccountRegistrySetEventFilter;

    "DolomiteMigratorSet(address)"(
      _dolomiteMigrator?: string | null
    ): DolomiteMigratorSetEventFilter;
    DolomiteMigratorSet(
      _dolomiteMigrator?: string | null
    ): DolomiteMigratorSetEventFilter;

    "EventEmitterSet(address)"(
      _eventEmitter?: string | null
    ): EventEmitterSetEventFilter;
    EventEmitterSet(_eventEmitter?: string | null): EventEmitterSetEventFilter;

    "ExpirySet(address)"(_expiry?: string | null): ExpirySetEventFilter;
    ExpirySet(_expiry?: string | null): ExpirySetEventFilter;

    "GenericTraderProxySet(address)"(
      _genericTraderProxy?: string | null
    ): GenericTraderProxySetEventFilter;
    GenericTraderProxySet(
      _genericTraderProxy?: string | null
    ): GenericTraderProxySetEventFilter;

    "LiquidatorAssetRegistrySet(address)"(
      _liquidatorAssetRegistry?: string | null
    ): LiquidatorAssetRegistrySetEventFilter;
    LiquidatorAssetRegistrySet(
      _liquidatorAssetRegistry?: string | null
    ): LiquidatorAssetRegistrySetEventFilter;

    "OracleAggregatorSet(address)"(
      _oracleAggregator?: string | null
    ): OracleAggregatorSetEventFilter;
    OracleAggregatorSet(
      _oracleAggregator?: string | null
    ): OracleAggregatorSetEventFilter;

    "RedstonePriceOracleSet(address)"(
      _redstonePriceOracle?: string | null
    ): RedstonePriceOracleSetEventFilter;
    RedstonePriceOracleSet(
      _redstonePriceOracle?: string | null
    ): RedstonePriceOracleSetEventFilter;

    "SlippageToleranceForPauseSentinelSet(uint256)"(
      _slippageTolerance?: null
    ): SlippageToleranceForPauseSentinelSetEventFilter;
    SlippageToleranceForPauseSentinelSet(
      _slippageTolerance?: null
    ): SlippageToleranceForPauseSentinelSetEventFilter;
  };

  estimateGas: {
    chainlinkPriceOracle(overrides?: CallOverrides): Promise<BigNumber>;

    dolomiteAccountRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    dolomiteMigrator(overrides?: CallOverrides): Promise<BigNumber>;

    eventEmitter(overrides?: CallOverrides): Promise<BigNumber>;

    expiry(overrides?: CallOverrides): Promise<BigNumber>;

    genericTraderProxy(overrides?: CallOverrides): Promise<BigNumber>;

    lazyInitialize(
      _dolomiteMigrator: string,
      _oracleAggregator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    liquidatorAssetRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    oracleAggregator(overrides?: CallOverrides): Promise<BigNumber>;

    ownerSetChainlinkPriceOracle(
      _chainlinkPriceOracle: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetDolomiteAccountRegistry(
      _dolomiteAccountRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetDolomiteMigrator(
      _dolomiteMigrator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetEventEmitter(
      _eventEmitter: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetExpiry(
      _expiry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetGenericTraderProxy(
      _genericTraderProxy: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetLiquidatorAssetRegistry(
      _liquidatorRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetOracleAggregator(
      _oracleAggregator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetRedstonePriceOracle(
      _redstonePriceOracle: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    ownerSetSlippageToleranceForPauseSentinel(
      _slippageToleranceForPauseSentinel: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    redstonePriceOracle(overrides?: CallOverrides): Promise<BigNumber>;

    slippageToleranceForPauseSentinel(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    slippageToleranceForPauseSentinelBase(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    chainlinkPriceOracle(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dolomiteAccountRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    dolomiteMigrator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    eventEmitter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    expiry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    genericTraderProxy(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lazyInitialize(
      _dolomiteMigrator: string,
      _oracleAggregator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    liquidatorAssetRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oracleAggregator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ownerSetChainlinkPriceOracle(
      _chainlinkPriceOracle: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetDolomiteAccountRegistry(
      _dolomiteAccountRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetDolomiteMigrator(
      _dolomiteMigrator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetEventEmitter(
      _eventEmitter: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetExpiry(
      _expiry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetGenericTraderProxy(
      _genericTraderProxy: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetLiquidatorAssetRegistry(
      _liquidatorRegistry: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetOracleAggregator(
      _oracleAggregator: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetRedstonePriceOracle(
      _redstonePriceOracle: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    ownerSetSlippageToleranceForPauseSentinel(
      _slippageToleranceForPauseSentinel: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    redstonePriceOracle(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    slippageToleranceForPauseSentinel(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    slippageToleranceForPauseSentinelBase(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
