/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICustomTestToken__factory } from "./ICustomTestToken__factory";
export { ICustomTestVaultToken__factory } from "./ICustomTestVaultToken__factory";
