/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDolomiteInterestSetter } from "./IDolomiteInterestSetter";
export type { IDolomiteMargin } from "./IDolomiteMargin";
export type { IDolomiteMarginAdmin } from "./IDolomiteMarginAdmin";
export type { IDolomitePriceOracle } from "./IDolomitePriceOracle";
